### ISSUE TITLE
COBOL: The END-IF color changes when it has a PERFORM inside

### ISSUE THREAD

**Issue by jonathanschmittblog** [noplay/vscode-rainbow-end#36]
Greetings, Julien!

First of all thanks for developing this amazing extension.

I encountered a problem when using the COBOL extension: 
- The END-IF color changes when it has a PERFORM inside

![image](https://user-images.githubusercontent.com/33349637/123264774-bcc14180-d4d0-11eb-82e2-c45fe1738b50.png)
![image](https://user-images.githubusercontent.com/33349637/123267653-a1a40100-d4d3-11eb-8e8a-086506b27725.png)

Not all PERFORMs will have an END-PERFORM. PERFORM UNTIL and PERFORM VARYNG only.
The simple PERFORM, command is just to call another paragraph/method so this one will not have an END-PERFORM.

**Comment by jonathanschmittblog** [comment]
It worked for me:

COBOL: {
    caseSensitive: false,
    ignoreInDelimiters: [],
    inlineOpenTokens: [],
    openTokens: ["perform *?until exit", "evalute", "perform( |\r|\n)*?varying(.|\r|\n)*?until", "if"],
    closeTokens: ["end-evalute", "end-perform", "end-if"],
    neutralTokens: ["else", "when"],
  },

**Comment by noplay** [comment]
Thanks a lot . Sound good to me

Can you open a pull request (in order to credit you for the change) ? I will release after.

**Comment by jonathanschmittblog** [comment]
Done! =D

Thanks, Julien!
