### ISSUE TITLE
New Version 0.7.11 does not work for Julia language 

### ISSUE THREAD

**Issue by ghost** [noplay/vscode-rainbow-end#43]
Dear Julien,

Rainbow end is very useful for helping to make Julia language more visible. Unfortunately the new version does not work for Julia language but the old version works remarkably well.

Cheers,
Joseph

**Comment by julien-duponchelle** [comment]
So sorry a 0.7.12 is coming , publication is in progress

**Comment by ghost** [comment]
Thanks is now works for Julia
