### ISSUE TITLE
Detection within comments

### ISSUE THREAD

**Issue by Moltenhead** [noplay/vscode-rainbow-end#5]
Hi there.
Just to report that the extension is matching key words within commentaries and that's breaking the feature.

That's a cool idea though. :)

EDIT : forgot to tell it was within ruby (maybe something like `(?<!<lang_comment_sign>)`)

**Comment by noplay** [comment]
Yeah I'm aware of this issue I hope one day to be able to implement #1 same issue wit strings 

I didn't found a proper way to implement it with regex, the best will be to implement a real parser and properly tokenize the file

**Comment by bjeanes** [comment]
Even using regex, it should be possible to avoid detecting "do" in the word "don't" as here:

![2019-05-08 at 1 13 pm](https://user-images.githubusercontent.com/2560/57346763-223c0200-7193-11e9-9e31-a08c3beed199.png)

**Comment by polvalente** [comment]
Maybe this issue can be closed now, @noplay
