### ISSUE TITLE
Extension incorrectly colors when keywords are part of other words

### ISSUE THREAD

**Issue by DianeLooney** [noplay/vscode-rainbow-end#8]
The following code snippet is incorrectly highlighted for me:

```
class OtherThing
  belongs_to :my_model, class_name: 'MyModel'
end

class MyModel
  has_one :other_things, class_name: 'OtherThing'
end
```
I would expect the color of the `class` and `end` that define `OtherThing` to match, and for the colors of the `class` and `end` around `MyModel` to match. They do not, because of the `class_name:` parameters to the `has_one` and `belongs_to` methods.

All other extensions are disabled for this screenshot.

![image](https://user-images.githubusercontent.com/27440221/58591789-10e79200-8235-11e9-9e93-db71d3078a86.png)

I think this is due to the escape of `.` here:

https://github.com/noplay/vscode-rainbow-end/blob/3b56ccbb1b444c13357e82ec6d9d6be0af70cc68/src/extension.ts#L59

Adding an additional `\` to the escape causes the regex to behave as I would expect, and to not match `class_name`:
```
const r1 = RegExp("(^[ \t]*|[^\n \t][ \t]+)(" + ['class','end'].join('|') + ")(\\s|\.|$)", "gm");
console.log("r1: ", r1.toString());
// r1:  /(^[ 	]*|[^\n 	][ 	]+)(class|end)(\s|.|$)/gm
// r1 matches?:  (4) ["class_", "", "class", "_", index: 0, input: "class_name", groups: undefined]
console.log("r1 matches?: ", r1.exec('class_name'));

const r2 = RegExp("(^[ \t]*|[^\n \t][ \t]+)(" + ['class','end'].join('|') + ")(\\s|\\.|$)", "gm");
console.log("r2: ", r2.toString());
console.log("r2 matches?: ", r2.exec('class_name'));
// r2:  /(^[ 	]*|[^\n 	][ 	]+)(class|end)(\s|\.|$)/gm
// r2 matches?:  null
```

It might be worthwhile to use `\\b` instead? I apologize for any misunderstandings in the code of the extension. :)

**Comment by noplay** [comment]
Oh yes \b seem a good idea. Do you think you can make a PR for it?

**Comment by DianeLooney** [comment]
PR is posted: https://github.com/noplay/vscode-rainbow-end/pull/9

**Comment by DianeLooney** [comment]
PR was merged. Closing.
